name: Daily Email

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --production
      - name: Baixar historico.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p data
          curl -f -H "Authorization: token $GITHUB_TOKEN" -L \
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/data/historico.json \
            -o data/historico.json || echo "[]" > data/historico.json
      - run: node scripts/daily-email.js
        env:
          EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
          EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
          EMAILJS_PRIVATE_KEY: ${{ secrets.EMAILJS_PRIVATE_KEY }}
          EMAILJS_RECIPIENTS: ${{ secrets.EMAILJS_RECIPIENTS }}
